" Disable vi compatibility
set nocompatible
syntax enable

" With some ideas from Martin Brochhaus' git repo:
" https://github.com/mbrochh/vim-as-a-python-ide

" Automatic reloading of vimrc
au! bufwritepost .vimrc source %


"" Color themes
hi SpellBad   ctermfg=Red     term=Reverse   guisp=Red     gui=undercurl ctermbg=White
hi SpellCap   ctermfg=Green   term=Reverse   guisp=Green   gui=undercurl ctermbg=White
hi SpellLocal ctermfg=Cyan    term=Underline guisp=Cyan    gui=undercurl ctermbg=White
hi SpellRare  ctermfg=Magenta term=underline guisp=Magenta gui=undercurl ctermbg=White

hi ExtraWhitespace ctermbg=red guibg=red
hi TabHighlight  ctermbg=lightgreen guibg=lightgreen

" Better copy & paste
" " When you want to paste large blocks of code into vim, press F2 before you
" " paste. At the bottom you should see ``-- INSERT (paste) --``.
"
set pastetoggle=<F2>
set clipboard=unnamed

" Rebind <Leader> key
" " I like to have it here because it is easier to reach than the default and
" " it is next to ``m`` and ``n`` which I use for navigating between tabs.
let mapleader = ","

" bind Ctrl+<movement> keys to move around the windows, instead of using
" Ctrl+w + <movement>
" " Every unnecessary keystroke that can be saved is good for your health :)
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" easier moving between tabs
map <Leader>n <esc>:tabprevious<CR>
map <Leader>m <esc>:tabnext<CR>
"
"
" " map sort function to a key
vnoremap <Leader>s :sort<CR>
"
"
" " easier moving of code blocks
" " Try to go into visual mode (v), then select several lines of code here and
" " then press ``>`` several times.
vnoremap < <gv " better indentation
vnoremap > >gv " better indentation

" Showing line numbers and length
set number " show line numbers
set tw=79 " width of document (used by gd)
set nowrap " don't automatically wrap on load
set fo-=t " don't automatically wrap text when typing
set wrap linebreak nolist "Break lines

set colorcolumn=80
highlight ColorColumn ctermbg=233

" Useful settings
set history=700
set undolevels=700

" Editing
set backspace=indent,eol,start  " sane backspacing
set shiftwidth=4                " more-or-less sane indents
set softtabstop=4               " make the <tab> key more useful
set expandtab                   " sane default
set noshiftround                " do NOT enforce the indent
set autoindent                  " automatic indent
set nosmartindent               " but no smart indent (ain't smart enough)
set tabstop=4                   " replace one tab by 4 spaces
set hidden                      " No need to save background buffers

" Replace tabs in python with 8 spaces
au BufNewFile,BufRead *.py set tabstop=8

"" Search should be case insensitive
set ignorecase                  " no case sensitive
set hlsearch
set incsearch
set smartcase

" Scrolling behaviour
set scrolloff=8 "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

""setlocal spell spelllang=en_us
""setlocal spelllang=de spell

" Spell checking
" To install spell checking (http://wiki.ubuntuusers.de/VIM/Tipps)
" - sudo apt-get install hunspell-de-de
" - mkdir -p ~/.vim/spell
" - In vim:   :mkspell ~/.vim/spell/de /usr/share/myspell/dicts/de-DE
" - new distributions: :mkspell ~/.vim/spell/de /usr/share/hunspell/de-DE
" - Prüfung aktivieren

if v:version >= 700
  set spelllang=en,de spell
  set spellfile=~/.vim/spell.utf-8.add
endif

if has("linebreak")
  let &sbr = nr2char(8618).' '  " Show ↪ at the beginning of wrapped lines
endif

filetype plugin on
if has('gui_running')
    set grepprg=grep\ -nH\ $*
    filetype indent on
    let g:tex_flavor='latex'
    " Disable folding in Latex
    let Tex_FoldedSections=""
    let Tex_FoldedEnvironments=""
    let Tex_FoldedMisc=""
endif

"" Use markdown syntax highlighting
"" Install to ~/.vim/bundle
"" git clone https://github.com/plasticboy/vim-markdown.git

"" Enable for .md files
au BufRead,BufNewFile *.md set filetype=markdown

" Show trailing whitespace.
au BufWinEnter * match ExtraWhitespace /\s\+$/

" Show tabs
au BufWinEnter * 2match TabHighlight /\t\+/

""Highlight long lines
if exists('+colorcolumn')
  set colorcolumn=80
  hi ColorColumn ctermbg=lightgrey guibg=lightgrey
endif

"" Sound off
set noerrorbells visualbell t_vb=
au GUIEnter * set visualbell t_vb=
set visualbell

"" Set mapping for soft linebreaks
map <silent> <Up> gk
imap <silent> <Up> <C-o>gk
map <silent> <Down> gj
imap <silent> <Down> <C-o>gj
map <silent> <home> g<home>
imap <silent> <home> <C-o>g<home>
map <silent> <End> g<End>
imap <silent> <End> <C-o>g<End>

"" Do not use gvim in full screen mode
if has("gui_running")
  "" Use 85 to ensure 80 columns marker is shown regardless of the line number
  "" at the beginning of the line
  set lines=40 columns=85
endif

"" Own commands (must start with capital letter)

"" Remove trailing whitespaces
command Rmws %s/\s\+$//
